/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/libraries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all libraries */
        get: operations["listLibraries"];
        put?: never;
        /** Create a library pointing at a local folder */
        post: operations["createLibrary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/libraries/{libraryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one library */
        get: operations["getLibrary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/libraries/{libraryId}/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start an async library scan job (ADR-0004) */
        post: operations["scanLibrary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/scan-jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll scan job state and counts */
        get: operations["getScanJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/libraries/{libraryId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List media items in a library */
        get: operations["listLibraryItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one media item */
        get: operations["getItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/items/{itemId}/playback-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Playback method and delivery URL for an item */
        get: operations["getPlaybackInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/items/{itemId}/subtitles/{trackId}.vtt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** WebVTT for one text subtitle track (ADR-0010) */
        get: operations["getSubtitleVtt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/items/{itemId}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Byte stream for playback (supports HTTP Range)
         * @description Serves the original file for directPlay items. Remux and transcode items are delivered as HLS sessions (ADR-0011).
         */
        get: operations["streamItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/items/{itemId}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start an HLS playback session for an item
         * @description ADR-0011. Returns 202 with sessionId and playlistUrl. Remux items get a stream-copy session, transcode items a re-encoding one; the shape is identical. Each POST creates a session; seek with ?startMs= on the playlist restarts that session in place. Concurrent sessions are capped via NIGHTJAR_HLS_MAX_SESSIONS (default 3).
         */
        post: operations["startTranscodeSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/sessions/{sessionId}/master.m3u8": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * HLS master playlist for a playback session
         * @description ADR-0008 / ADR-0010. Declares the single video rendition (index.m3u8) and optional SUBTITLES group. playlistUrl from session start points here. Seek via startMs uses the same window-move rules as the media playlist.
         */
        get: operations["getSessionMasterPlaylist"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/sessions/{sessionId}/index.m3u8": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * HLS media playlist for a playback session
         * @description Media playlist path is stable (ADR-0008). Segment URIs are relative init.mp4 / segNNN.m4s. Also accepts startMs for seek.
         */
        get: operations["getSessionPlaylist"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/sessions/{sessionId}/subs/{asset}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One-segment subtitle media playlist for a session track
         * @description ADR-0010. EXT-X-MEDIA URI target. References the item WebVTT URL for the snapshotted trackId.
         */
        get: operations["getSessionSubtitlePlaylist"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/sessions/{sessionId}/{asset}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** HLS init segment or media segment for a session */
        get: operations["getSessionAsset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Stop a playback session and reap its FFmpeg process */
        delete: operations["deleteTranscodeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/system/transcode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verified H.264 encode capabilities for this process
         * @description Startup detection-by-verification (ADR-0009). Each candidate is verified | failed | unavailable with a reason when not verified. preferredH264Encoder is what new HLS sessions use for -c:v.
         */
        get: operations["getTranscodeCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @example ok */
            status: string;
            version: string;
            core?: string;
        };
        Error: {
            error: string;
        };
        /** @enum {string} */
        LibraryKind: "movies" | "shows";
        /** @enum {string} */
        MediaKind: "movie" | "episode" | "unknown";
        /**
         * @description indexed = walk+filename done, codecs pending; probed = ffprobe ok; error = ffprobe failed (see scanError).
         * @enum {string}
         */
        ProbeStatus: "indexed" | "probed" | "error";
        /** @enum {string} */
        ScanJobState: "queued" | "indexing" | "probing" | "completed" | "failed";
        /**
         * @description directPlay = browser plays the original file; remux = same codecs in a container the client cannot open, delivered as a stream-copy HLS session; transcode = needs re-encoding, delivered as an encoding HLS session. Pending or failed probes report transcode.
         * @enum {string}
         */
        PlaybackMethod: "directPlay" | "remux" | "transcode";
        TranscodeSession: {
            sessionId: string;
            /** Format: int64 */
            itemId: number;
            /** @description Path to the HLS master playlist for this session (master.m3u8). The media playlist remains at index.m3u8 (ADR-0008). */
            playlistUrl: string;
            /** @description FFmpeg encoder currently used by this session, or "copy" when the session stream-copies video (remux). */
            videoEncoder: string;
            /**
             * @description Whether videoEncoder is a hardware encoder, a software encoder, or a stream copy.
             * @enum {string}
             */
            encoderKind: "hardware" | "software" | "copy";
        };
        Library: {
            /** Format: int64 */
            id: number;
            name: string;
            path: string;
            kind: components["schemas"]["LibraryKind"];
            /** Format: int64 */
            itemCount: number;
        };
        CreateLibraryRequest: {
            name: string;
            path: string;
            kind: components["schemas"]["LibraryKind"];
        };
        MediaItem: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            libraryId: number;
            path: string;
            title: string;
            kind: components["schemas"]["MediaKind"];
            year?: number | null;
            season?: number | null;
            episode?: number | null;
            /** Format: int64 */
            durationMs?: number | null;
            container?: string | null;
            videoCodec?: string | null;
            audioCodec?: string | null;
            width?: number | null;
            height?: number | null;
            /** Format: int64 */
            sizeBytes: number;
            probeStatus: components["schemas"]["ProbeStatus"];
            scanError?: string | null;
            playbackMethod: components["schemas"]["PlaybackMethod"];
        };
        ScanJobAccepted: {
            /** Format: int64 */
            jobId: number;
            /** Format: int64 */
            libraryId: number;
        };
        ScanJob: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            libraryId: number;
            state: components["schemas"]["ScanJobState"];
            added: number;
            updated: number;
            removed: number;
            unchanged: number;
            probed: number;
            errors: number;
            /**
             * Format: int64
             * @description Wall time of the index pass; Gate 1 measures this.
             */
            indexDurationMs?: number | null;
            /** Format: int64 */
            probeDurationMs?: number | null;
            error?: string | null;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            finishedAt?: string | null;
        };
        PlaybackInfo: {
            /** Format: int64 */
            itemId: number;
            playbackMethod: components["schemas"]["PlaybackMethod"];
            /** @description Why the decision engine chose this method */
            reason: string;
            /** @description Present only when playbackMethod is directPlay */
            streamUrl?: string;
            /** @description Present when playbackMethod is remux or transcode. POST here to start an HLS session (ADR-0011). */
            sessionsUrl?: string;
            /** @description Source MIME for directPlay; application/vnd.apple.mpegurl for session playback. */
            mimeType: string;
            /** Format: int64 */
            durationMs?: number | null;
            container?: string | null;
            videoCodec?: string | null;
            audioCodec?: string | null;
            /** @description Audio tracks in the source (ADR-0012). Listed the same way for directPlay, remux, and transcode: the client asks for a trackId and never reasons about the delivery path to find tracks. Direct play switches client-side; sessions take audioTrackId at start. */
            audioTracks?: components["schemas"]["AudioTrack"][];
            /** @description Text subtitle tracks (ADR-0010). Embedded and filesystem sidecars share one shape; differ by source. Listed the same way for directPlay, remux, and transcode. Delivery is via track elements or HLS EXT-X-MEDIA depending on the stream; clients do not branch on method to find tracks. */
            subtitleTracks?: components["schemas"]["SubtitleTrack"][];
        };
        AudioTrack: {
            /** @description Stable id `e{streamIndex}`, the same scheme as embedded subtitles (ADR-0010 / ADR-0012). */
            trackId: string;
            /** @description Source codec (aac, ac3, eac3, dts, ...) */
            codec: string;
            /** @description Normalised ISO 639-1 when known; null if unlabelled */
            language?: string | null;
            /** @description Channel count. Tracks above the client ceiling are downmixed to stereo by the session with an explicit pan matrix. */
            channels: number;
            /** @description FFmpeg layout name (stereo, 5.1, 7.1, ...) when reported */
            channelLayout?: string | null;
            /** @description Optional title tag from the container (e.g. Commentary) */
            label?: string | null;
            /** @description Container default disposition. Exactly one track is default: the flagged one, else the first. */
            default: boolean;
            /** @description Absolute ffprobe stream index */
            streamIndex: number;
        };
        SubtitleTrack: {
            /** @description Stable id used in the VTT URL. Embedded `e{N}`; sidecar `s` / `s-{suffix}` from the filename (ADR-0010). */
            trackId: string;
            /** @enum {string} */
            source: "embedded" | "sidecar";
            /** @description Source codec or sidecar format (subrip, srt, vtt, ass, ...) */
            codec: string;
            /** @description Normalised ISO 639-1 when known; null if unlabelled */
            language?: string | null;
            /** @description Optional title tag from the container (embedded) */
            label?: string | null;
            /** @description Forced-subtitle flag (selection differs from full dialogue) */
            forced: boolean;
            /** @description SDH / hearing-impaired flag from the sidecar name */
            sdh: boolean;
            /** @description Absolute ffprobe stream index when source is embedded */
            streamIndex?: number | null;
            /** @description GET path for the WebVTT body when this track is served. Absent for ASS/SSA and other non-serveable tracks that are still listed. */
            url?: string | null;
        };
        /**
         * @description verified = short encode+demux succeeded; failed = advertised but verify failed; unavailable = not in this ffmpeg build.
         * @enum {string}
         */
        EncoderStatus: "verified" | "failed" | "unavailable";
        EncoderCandidate: {
            /** @description FFmpeg encoder name (e.g. libx264, h264_videotoolbox) */
            name: string;
            /** @description Backend family (software, videotoolbox, nvenc, qsv, vaapi, ...) */
            backend: string;
            status: components["schemas"]["EncoderStatus"];
            /** @description Required when status is not verified; null when verified */
            reason?: string | null;
        };
        TranscodeCapabilities: {
            ffmpegVersion?: string | null;
            /** @description Encoder name used for new HLS sessions (-c:v) */
            preferredH264Encoder: string;
            encoders: components["schemas"]["EncoderCandidate"][];
        };
    };
    responses: never;
    parameters: {
        LibraryId: number;
        ItemId: number;
        JobId: number;
        SessionId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listLibraries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Libraries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        libraries: components["schemas"]["Library"][];
                    };
                };
            };
        };
    };
    createLibrary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLibraryRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Library"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getLibrary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                libraryId: components["parameters"]["LibraryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Library */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Library"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    scanLibrary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                libraryId: components["parameters"]["LibraryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scan job accepted (or existing active job returned) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanJobAccepted"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getScanJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scan job status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanJob"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listLibraryItems: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                libraryId: components["parameters"]["LibraryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["MediaItem"][];
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaItem"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getPlaybackInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Playback info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaybackInfo"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getSubtitleVtt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["ItemId"];
                /** @description Stable track id (ADR-0010): `e{streamIndex}` for embedded, `s` / `s-{suffix}` for filesystem sidecars. */
                trackId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description WebVTT body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/vtt": string;
                };
            };
            /** @description Item or serveable subtitle track not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    streamItem: {
        parameters: {
            query?: never;
            header?: {
                Range?: string;
            };
            path: {
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entire file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Partial content */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Item needs an HLS session; POST /api/v0/items/{itemId}/sessions */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Range not satisfiable */
            416: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    startTranscodeSession: {
        parameters: {
            query?: {
                /** @description Encode window start in milliseconds (default 0) */
                startMs?: number;
                /** @description Audio track to map, from playbackInfo.audioTracks (ADR-0012). Defaults to the flagged default track, else the first. Switching audio starts a new session at the current position and DELETEs the old one. */
                audioTrackId?: string;
            };
            header?: never;
            path: {
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session started for this item */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscodeSession"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Item direct plays, or is not ready for a session */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Session cap full; retry shortly */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getSessionMasterPlaylist: {
        parameters: {
            query?: {
                /** @description Encode window start; a change restarts this session there */
                startMs?: number;
            };
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HLS master playlist */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.apple.mpegurl": string;
                };
            };
            /** @description Session not found or playlist not ready yet */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getSessionPlaylist: {
        parameters: {
            query?: {
                /** @description Encode window start; a change restarts this session there */
                startMs?: number;
            };
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HLS playlist */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.apple.mpegurl": string;
                };
            };
            /** @description Session not found or playlist not ready yet */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getSessionSubtitlePlaylist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
                /** @description {trackId}.m3u8 (e.g. e2.m3u8, s-en.m3u8) */
                asset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HLS subtitle media playlist */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.apple.mpegurl": string;
                };
            };
            /** @description Session or track not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getSessionAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
                asset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Segment bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Session or asset not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Segment not on disk yet (encoder still cooking). Retryable; do not treat as a permanent miss. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteTranscodeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stopped (or already gone) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getTranscodeCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Capability readout */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscodeCapabilities"];
                };
            };
        };
    };
}
