/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/libraries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all libraries */
        get: operations["listLibraries"];
        put?: never;
        /** Create a library pointing at a local folder */
        post: operations["createLibrary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/libraries/{libraryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one library */
        get: operations["getLibrary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/libraries/{libraryId}/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start an async library scan job (ADR-0004) */
        post: operations["scanLibrary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/scan-jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll scan job state and counts */
        get: operations["getScanJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/libraries/{libraryId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List media items in a library */
        get: operations["listLibraryItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one media item */
        get: operations["getItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/items/{itemId}/playback-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Playback method, remux state, and stream URL for an item */
        get: operations["getPlaybackInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/items/{itemId}/remux": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start (or reuse) a background remux for an item
         * @description Async job per ADR-0006. Returns the current state immediately; poll playback-info until remuxState is ready. When all remux slots are busy the state stays notStarted with a reason; clients re-POST on each poll tick while they see notStarted.
         */
        post: operations["startRemux"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/items/{itemId}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Byte stream for playback (supports HTTP Range)
         * @description Serves the original file for directPlay items and the remuxed MP4 for remux items once remuxState is ready.
         */
        get: operations["streamItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @example ok */
            status: string;
            version: string;
            core?: string;
        };
        Error: {
            error: string;
        };
        /** @enum {string} */
        LibraryKind: "movies" | "shows";
        /** @enum {string} */
        MediaKind: "movie" | "episode" | "unknown";
        /**
         * @description indexed = walk+filename done, codecs pending; probed = ffprobe ok; error = ffprobe failed (see scanError).
         * @enum {string}
         */
        ProbeStatus: "indexed" | "probed" | "error";
        /** @enum {string} */
        ScanJobState: "queued" | "indexing" | "probing" | "completed" | "failed";
        /**
         * @description directPlay = browser plays the original file; remux = same codecs repackaged to MP4 by a background job; transcode = needs re-encoding, not available yet. Pending or failed probes report transcode.
         * @enum {string}
         */
        PlaybackMethod: "directPlay" | "remux" | "transcode";
        /**
         * @description Only meaningful when playbackMethod is remux. notStarted may carry a busy reason when all remux slots are in use; clients re-POST while they see it (ADR-0006).
         * @enum {string}
         */
        RemuxState: "notStarted" | "preparing" | "ready" | "failed";
        RemuxAccepted: {
            /** Format: int64 */
            itemId: number;
            remuxState: components["schemas"]["RemuxState"];
            /** @description Why the job is not running yet, or why it failed */
            reason?: string;
        };
        Library: {
            /** Format: int64 */
            id: number;
            name: string;
            path: string;
            kind: components["schemas"]["LibraryKind"];
            /** Format: int64 */
            itemCount: number;
        };
        CreateLibraryRequest: {
            name: string;
            path: string;
            kind: components["schemas"]["LibraryKind"];
        };
        MediaItem: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            libraryId: number;
            path: string;
            title: string;
            kind: components["schemas"]["MediaKind"];
            year?: number | null;
            season?: number | null;
            episode?: number | null;
            /** Format: int64 */
            durationMs?: number | null;
            container?: string | null;
            videoCodec?: string | null;
            audioCodec?: string | null;
            width?: number | null;
            height?: number | null;
            /** Format: int64 */
            sizeBytes: number;
            probeStatus: components["schemas"]["ProbeStatus"];
            scanError?: string | null;
            playbackMethod: components["schemas"]["PlaybackMethod"];
        };
        ScanJobAccepted: {
            /** Format: int64 */
            jobId: number;
            /** Format: int64 */
            libraryId: number;
        };
        ScanJob: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            libraryId: number;
            state: components["schemas"]["ScanJobState"];
            added: number;
            updated: number;
            removed: number;
            unchanged: number;
            probed: number;
            errors: number;
            /**
             * Format: int64
             * @description Wall time of the index pass; Gate 1 measures this.
             */
            indexDurationMs?: number | null;
            /** Format: int64 */
            probeDurationMs?: number | null;
            error?: string | null;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            finishedAt?: string | null;
        };
        PlaybackInfo: {
            /** Format: int64 */
            itemId: number;
            playbackMethod: components["schemas"]["PlaybackMethod"];
            /** @description Present when playbackMethod is remux */
            remuxState?: components["schemas"]["RemuxState"];
            /** @description Present when remuxState is failed or start is blocked */
            remuxError?: string;
            /** @description Why the decision engine chose this method */
            reason: string;
            /** @description Present only when the item is playable now: directPlay, or remux with remuxState ready. */
            streamUrl?: string;
            /** @description video/mp4 for remux regardless of the source container */
            mimeType: string;
            /** Format: int64 */
            durationMs?: number | null;
            container?: string | null;
            videoCodec?: string | null;
            audioCodec?: string | null;
        };
    };
    responses: never;
    parameters: {
        LibraryId: number;
        ItemId: number;
        JobId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listLibraries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Libraries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        libraries: components["schemas"]["Library"][];
                    };
                };
            };
        };
    };
    createLibrary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLibraryRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Library"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getLibrary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                libraryId: components["parameters"]["LibraryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Library */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Library"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    scanLibrary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                libraryId: components["parameters"]["LibraryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scan job accepted (or existing active job returned) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanJobAccepted"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getScanJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scan job status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanJob"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listLibraryItems: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                libraryId: components["parameters"]["LibraryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["MediaItem"][];
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaItem"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getPlaybackInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Playback info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaybackInfo"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    startRemux: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Remux state after this request */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemuxAccepted"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Item does not use the remux method */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    streamItem: {
        parameters: {
            query?: never;
            header?: {
                Range?: string;
            };
            path: {
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entire file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Partial content */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Remux not ready; POST remux and poll playback-info */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Item needs transcoding, which is not available yet */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Range not satisfiable */
            416: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
