//! Deterministic generated-stress harness for the filename parser.
//!
//! This is a bounded robustness and convention check, not an accuracy
//! benchmark. It generates fictional names in memory from explicit template
//! families, parses them with the shipped `nightjar-core` API, and asserts the
//! stable fields each convention defines. Ambiguous and adverse families assert
//! only safety invariants: no panic, a bounded input, and no invented episode or
//! year where the template supplies none.
//!
//! The generator is deterministic. The seed, version, per-family counts, input
//! bound and resource budget are recorded in `stress/manifest.json` and
//! cross-checked here. The generated bulk output is **not** committed: the run
//! rebuilds it from the seed, and a fingerprint over the generated inputs is
//! compared with the manifest so a changed seed or family accounting fails.
//!
//! Nothing here reads the network, the sealed held-out set, or any private
//! path. The names are invented; none is a real title.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::time::Instant;

use nightjar_core::{
    FolderContext, MediaKind, ParsedName, parse_filename, parse_filename_in, parse_with_parent,
};
use serde_json::Value;

/// Manifest schema version for this file.
const SCHEMA_VERSION: i64 = 1;
/// Generator version. Bump only when the templates change; the manifest must
/// then be regenerated with the new counts and fingerprint.
const GENERATOR_VERSION: i64 = 2;
/// Fixed generator seed. Recorded in the manifest; the fingerprint binds the
/// generated population to it.
const SEED: u64 = 0x6E69_6768_746A_6172;
/// Maximum input size, in bytes, for one generated name. A chosen ceiling, not
/// a measurement: 4096 is the smallest power of two that holds the longest
/// template here with room to spare. It governs this generated population only;
/// a real basename can be longer and no parser contract may assume it.
const MAX_INPUT_BYTES: usize = 4096;
/// Local case budget for this run. A chosen ceiling derived from the declared
/// families: twelve families totalling 334 cases, so 1024 leaves headroom while
/// refusing unbounded generation. It is evidence about this run, not a global
/// default or a parser limit.
const LOCAL_CASE_BUDGET: usize = 1024;
/// Local generated-byte budget for this run, in bytes. A chosen one-mebibyte
/// ceiling; the generated population measured 16312 bytes on this checkout,
/// about 64x under. It bounds this run's allocation only, not a library size.
const LOCAL_BYTE_BUDGET: u64 = 1 << 20;
/// Hard ceiling on generated cases. A chosen backstop so a corrupted manifest
/// cannot raise the work past it, independent of the local budget above. It
/// governs this harness only.
const HARD_MAX_CASES: usize = 4096;
/// Hard ceiling on one generated input, in bytes. A chosen backstop for a
/// corrupted manifest, 16x `MAX_INPUT_BYTES`. It governs this harness only and
/// is not a parser contract.
const HARD_MAX_INPUT_BYTES: usize = 65536;
/// Hard ceiling on total generated bytes. A chosen backstop for a corrupted
/// manifest, 4x `LOCAL_BYTE_BUDGET`. It governs this harness only.
const HARD_MAX_BYTES: u64 = 4 * 1024 * 1024;

/// One family and its explicit, independently declared case count. Each entry
/// counts as one family; variations inside a family are not separate evidence.
type Builder = fn(usize, &mut Rng, usize) -> Vec<Case>;

const FAMILIES: [(&str, usize, Builder); 12] = [
    ("numeric_title_year", 30, build_numeric_title_year),
    ("scene_film", 30, build_scene_film),
    ("unicode_title", 24, build_unicode_title),
    ("missing_year", 24, build_missing_year),
    ("sxxeyy_nxnn", 40, build_sxxeyy_nxnn),
    ("season_folder", 24, build_season_folder),
    (
        "seasonless_date_absolute",
        36,
        build_seasonless_date_absolute,
    ),
    ("multi_episode", 32, build_multi_episode),
    ("season_zero", 20, build_season_zero),
    ("extras_editions", 28, build_extras_editions),
    ("misleading_tokens", 30, build_misleading_tokens),
    ("malformed_size", 16, build_malformed_size),
];

const NUMERIC_TITLES: &[&str] = &["7", "13", "42", "99", "121", "256", "512", "808"];
const FILM_TITLES: &[&str] = &[
    "Silent Harbor",
    "Crimson River",
    "Northern Lights",
    "Echo Chamber",
    "Glass Horizon",
    "Iron Meadow",
    "Velvet Sky",
    "Paper Lantern",
    "Copper Vale",
    "Winter Orchard",
];
const SHOW_NAMES: &[&str] = &[
    "Starfall",
    "Nightport",
    "Quiet Signal",
    "Harbor Line",
    "Red Meridian",
    "Ash Grove",
    "Bright Anchor",
    "Slow Comet",
];
const UNICODE_TITLES: &[&str] = &[
    "Café Nocturne",
    "Münchner Träume",
    "Zoë und das Licht",
    "Северное Сияние",
    "神隠しの森",
    "Été Rouge",
    "Åndeløs",
    "Nébuleuse",
];
const RELEASES: &[&str] = &[
    "1080p.BluRay.x264-GRP",
    "720p.WEB-DL.AAC",
    "2160p.HDR10.HEVC",
    "1080p.BluRay.DTS",
    "480p.DVDRip.XviD",
];
const EDITIONS: &[&str] = &[
    "Extended",
    "IMAX",
    "Remastered",
    "Anniversary",
    "Collectors",
];
/// Release tokens the parser's `TITLE_JUNK` lists (`proper`, `repack`). They
/// carry no identity and must not change the fields a name defines.
const RELEASE_TOKENS: &[&str] = &["Proper", "Repack"];

/// A small deterministic PRNG (SplitMix64). It exists only to vary the
/// generated population from the seed; it is not a security primitive.
struct Rng(u64);

impl Rng {
    fn new(seed: u64) -> Self {
        Self(seed)
    }

    fn next_u64(&mut self) -> u64 {
        self.0 = self.0.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.0;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }

    fn below(&mut self, n: usize) -> usize {
        (self.next_u64() % n as u64) as usize
    }

    fn pick<'a, T>(&mut self, items: &'a [T]) -> &'a T {
        &items[self.below(items.len())]
    }

    fn range(&mut self, lo: i64, hi: i64) -> i64 {
        lo + (self.next_u64() % ((hi - lo + 1) as u64)) as i64
    }
}

/// A field assertion. Positive families list the fields their convention
/// defines; adverse families list only the absences their safety contract
/// guarantees.
#[derive(Clone, Debug)]
enum Check {
    Title(String),
    Kind(MediaKind),
    Year(i32),
    YearNone,
    Season(i32),
    SeasonNone,
    Episode(i32),
    EpisodeNone,
    EpisodeEnd(i32),
    EpisodeEndNone,
    Absolute(bool),
}

/// How to feed the name to the parser. Folder context is part of the
/// season-folder family; everything else is a bare basename.
#[derive(Clone, Debug)]
enum Mode {
    Plain,
    Folder {
        folder_title: Option<String>,
        season: Option<i32>,
    },
    Parent(String),
}

#[derive(Clone, Debug)]
struct Case {
    family: &'static str,
    input: String,
    mode: Mode,
    checks: Vec<Check>,
}

#[derive(Clone, Debug)]
struct Manifest {
    schema_version: i64,
    generator_version: i64,
    seed: u64,
    total_cases: usize,
    families: BTreeMap<String, usize>,
    max_input_bytes: usize,
    local_case_budget: usize,
    local_byte_budget: u64,
    fingerprint: u64,
}

fn dotted(title: &str) -> String {
    title.replace(' ', ".")
}

fn plain(family: &'static str, input: String, checks: Vec<Check>) -> Case {
    Case {
        family,
        input,
        mode: Mode::Plain,
        checks,
    }
}

fn folder(
    family: &'static str,
    input: String,
    folder_title: Option<&str>,
    season: Option<i32>,
    checks: Vec<Check>,
) -> Case {
    Case {
        family,
        input,
        mode: Mode::Folder {
            folder_title: folder_title.map(str::to_string),
            season,
        },
        checks,
    }
}

fn parent(family: &'static str, input: String, parent_name: &str, checks: Vec<Check>) -> Case {
    Case {
        family,
        input,
        mode: Mode::Parent(parent_name.to_string()),
        checks,
    }
}

fn build_numeric_title_year(count: usize, rng: &mut Rng, _max: usize) -> Vec<Case> {
    let mut out = Vec::with_capacity(count);
    for i in 0..count {
        let title = *rng.pick(NUMERIC_TITLES);
        let year = rng.range(1912, 2017) as i32;
        let input = if i % 2 == 0 {
            format!("{title} ({year}).mkv")
        } else {
            format!("{title} ({year}).1080p.BluRay.mkv")
        };
        out.push(plain(
            "numeric_title_year",
            input,
            vec![
                Check::Title(title.to_string()),
                Check::Year(year),
                Check::Kind(MediaKind::Movie),
                Check::SeasonNone,
                Check::EpisodeNone,
            ],
        ));
    }
    out
}

fn build_scene_film(count: usize, rng: &mut Rng, _max: usize) -> Vec<Case> {
    let mut out = Vec::with_capacity(count);
    for i in 0..count {
        let title = *rng.pick(FILM_TITLES);
        let year = rng.range(1900, 2019) as i32;
        let release = *rng.pick(RELEASES);
        let input = match i % 3 {
            0 => format!("{}.{year}.{release}.mkv", dotted(title)),
            1 => format!("{title} ({year}).mkv"),
            _ => format!("{}.{year}.mkv", dotted(title)),
        };
        out.push(plain(
            "scene_film",
            input,
            vec![
                Check::Title(title.to_string()),
                Check::Year(year),
                Check::Kind(MediaKind::Movie),
                Check::SeasonNone,
                Check::EpisodeNone,
            ],
        ));
    }
    out
}

fn build_unicode_title(count: usize, rng: &mut Rng, _max: usize) -> Vec<Case> {
    let mut out = Vec::with_capacity(count);
    for i in 0..count {
        let title = *rng.pick(UNICODE_TITLES);
        let year = rng.range(1900, 2019) as i32;
        let input = if i % 2 == 0 {
            format!("{}.{year}.1080p.mkv", dotted(title))
        } else {
            format!("{title} ({year}).mkv")
        };
        out.push(plain(
            "unicode_title",
            input,
            vec![
                Check::Title(title.to_string()),
                Check::Year(year),
                Check::Kind(MediaKind::Movie),
                Check::SeasonNone,
                Check::EpisodeNone,
            ],
        ));
    }
    out
}

fn build_missing_year(count: usize, rng: &mut Rng, _max: usize) -> Vec<Case> {
    let mut out = Vec::with_capacity(count);
    for i in 0..count {
        let title = *rng.pick(FILM_TITLES);
        let input = match i % 3 {
            0 => format!("{}.1080p.BluRay.x264.mkv", dotted(title)),
            1 => format!("{}.WEB-DL.mkv", dotted(title)),
            _ => format!("{}.BluRay.mkv", dotted(title)),
        };
        out.push(plain(
            "missing_year",
            input,
            vec![
                Check::Title(title.to_string()),
                Check::YearNone,
                Check::Kind(MediaKind::Movie),
                Check::SeasonNone,
                Check::EpisodeNone,
            ],
        ));
    }
    out
}

fn build_sxxeyy_nxnn(count: usize, rng: &mut Rng, _max: usize) -> Vec<Case> {
    let mut out = Vec::with_capacity(count);
    for i in 0..count {
        let show = *rng.pick(SHOW_NAMES);
        let season = rng.range(1, 12) as i32;
        let episode = rng.range(1, 30) as i32;
        let input = match i % 3 {
            0 => format!("{show}.S{season:02}E{episode:02}.mkv"),
            1 => format!("{show}.{season}x{episode:02}.mkv"),
            _ => format!("{show}.S{season}E{episode}.mkv"),
        };
        out.push(plain(
            "sxxeyy_nxnn",
            input,
            vec![
                Check::Title(show.to_string()),
                Check::Kind(MediaKind::Episode),
                Check::Season(season),
                Check::Episode(episode),
                Check::EpisodeEndNone,
                Check::Absolute(false),
            ],
        ));
    }
    out
}

fn build_season_folder(count: usize, rng: &mut Rng, _max: usize) -> Vec<Case> {
    let mut out = Vec::with_capacity(count);
    for i in 0..count {
        let show = *rng.pick(SHOW_NAMES);
        let season = rng.range(1, 12) as i32;
        let episode = rng.range(1, 30) as i32;
        let folder_season = rng.range(1, 12) as i32;
        let case = match i % 5 {
            0 => folder(
                "season_folder",
                format!("S{season:02}E{episode:02}.mkv"),
                Some(show),
                Some(folder_season),
                vec![
                    Check::Title(show.to_string()),
                    Check::Kind(MediaKind::Episode),
                    Check::Season(season),
                    Check::Episode(episode),
                ],
            ),
            1 => folder(
                "season_folder",
                format!("S{season:02}E{episode:02}.mkv"),
                None,
                Some(folder_season),
                vec![
                    Check::Title(String::new()),
                    Check::Kind(MediaKind::Episode),
                    Check::Season(season),
                    Check::Episode(episode),
                ],
            ),
            2 => parent(
                "season_folder",
                format!("S{season:02}E{episode:02}.mkv"),
                show,
                vec![
                    Check::Title(show.to_string()),
                    Check::Kind(MediaKind::Episode),
                    Check::Season(season),
                    Check::Episode(episode),
                ],
            ),
            3 => folder(
                "season_folder",
                format!("{show}.E{episode:02}.mkv"),
                None,
                Some(folder_season),
                vec![
                    Check::Title(show.to_string()),
                    Check::Kind(MediaKind::Episode),
                    Check::SeasonNone,
                    Check::Episode(episode),
                    Check::Absolute(true),
                ],
            ),
            _ => folder(
                "season_folder",
                format!("{show}.S{season:02}E{episode:02}.mkv"),
                Some("Wrong Folder Name"),
                Some(folder_season),
                vec![
                    Check::Title(show.to_string()),
                    Check::Kind(MediaKind::Episode),
                    Check::Season(season),
                    Check::Episode(episode),
                ],
            ),
        };
        out.push(case);
    }
    out
}

fn build_seasonless_date_absolute(count: usize, rng: &mut Rng, _max: usize) -> Vec<Case> {
    let mut out = Vec::with_capacity(count);
    for i in 0..count {
        let show = *rng.pick(SHOW_NAMES);
        let episode = rng.range(1, 30) as i32;
        let year = rng.range(1950, 2019) as i32;
        let case = match i % 6 {
            0 => plain(
                "seasonless_date_absolute",
                format!("{show}.E{episode:02}.mkv"),
                vec![
                    Check::Title(show.to_string()),
                    Check::Kind(MediaKind::Episode),
                    Check::Episode(episode),
                    Check::SeasonNone,
                    Check::Absolute(true),
                ],
            ),
            1 => plain(
                "seasonless_date_absolute",
                format!("{show}.Ep{episode:02}.mkv"),
                vec![
                    Check::Title(show.to_string()),
                    Check::Kind(MediaKind::Episode),
                    Check::Episode(episode),
                    Check::SeasonNone,
                    Check::Absolute(true),
                ],
            ),
            2 => plain(
                "seasonless_date_absolute",
                format!("{show}.E{episode:02}.1080p.mkv"),
                vec![
                    Check::Title(show.to_string()),
                    Check::Kind(MediaKind::Episode),
                    Check::Episode(episode),
                    Check::SeasonNone,
                    Check::Absolute(true),
                ],
            ),
            3 => plain(
                "seasonless_date_absolute",
                format!("{year}.01.10 - {show} Talk Show.mkv"),
                vec![
                    Check::Title(String::new()),
                    Check::Year(year),
                    Check::Kind(MediaKind::Movie),
                    Check::SeasonNone,
                    Check::EpisodeNone,
                ],
            ),
            4 => plain(
                "seasonless_date_absolute",
                format!("{year}.01.10 - {show} Talk Show.E{episode:02}.mkv"),
                vec![
                    Check::Title(format!("{show} Talk Show")),
                    Check::Kind(MediaKind::Episode),
                    Check::Episode(episode),
                    Check::SeasonNone,
                    Check::Absolute(true),
                    Check::YearNone,
                ],
            ),
            _ => plain(
                "seasonless_date_absolute",
                format!("{year}0101 - {show}.ep{episode:02}.mkv"),
                vec![
                    Check::Title(show.to_string()),
                    Check::Kind(MediaKind::Episode),
                    Check::Episode(episode),
                    Check::SeasonNone,
                    Check::Absolute(true),
                ],
            ),
        };
        out.push(case);
    }
    out
}

fn build_multi_episode(count: usize, rng: &mut Rng, _max: usize) -> Vec<Case> {
    let mut out = Vec::with_capacity(count);
    for i in 0..count {
        let show = *rng.pick(SHOW_NAMES);
        let season = rng.range(1, 10) as i32;
        let start = rng.range(1, 20) as i32;
        let span = rng.range(1, 3) as i32;
        let end = start + span;
        let case = match i % 4 {
            0 => plain(
                "multi_episode",
                format!("{show}.S{season:02}E{start:02}-{end:02}.mkv"),
                vec![
                    Check::Title(show.to_string()),
                    Check::Kind(MediaKind::Episode),
                    Check::Season(season),
                    Check::Episode(start),
                    Check::EpisodeEnd(end),
                    Check::Absolute(false),
                ],
            ),
            1 => plain(
                "multi_episode",
                format!("{show}.S{season:02}E{start:02}-E{end:02}.mkv"),
                vec![
                    Check::Title(show.to_string()),
                    Check::Kind(MediaKind::Episode),
                    Check::Season(season),
                    Check::Episode(start),
                    Check::EpisodeEnd(end),
                    Check::Absolute(false),
                ],
            ),
            2 => plain(
                "multi_episode",
                format!("{show}.{season}x{start:02}-{end:02}.mkv"),
                vec![
                    Check::Title(show.to_string()),
                    Check::Kind(MediaKind::Episode),
                    Check::Season(season),
                    Check::Episode(start),
                    Check::EpisodeEnd(end),
                    Check::Absolute(false),
                ],
            ),
            _ => {
                let last = end + 1;
                plain(
                    "multi_episode",
                    format!("{show}.{season}x{start:02}-{end:02}-{last:02}.mkv"),
                    vec![
                        Check::Title(show.to_string()),
                        Check::Kind(MediaKind::Episode),
                        Check::Season(season),
                        Check::Episode(start),
                        Check::EpisodeEnd(last),
                        Check::Absolute(false),
                    ],
                )
            }
        };
        out.push(case);
    }
    out
}

fn build_season_zero(count: usize, rng: &mut Rng, _max: usize) -> Vec<Case> {
    let mut out = Vec::with_capacity(count);
    for i in 0..count {
        let show = *rng.pick(SHOW_NAMES);
        let episode = rng.range(1, 12) as i32;
        let case = if i % 2 == 0 {
            plain(
                "season_zero",
                format!("{show}.S00E{episode:02}.mkv"),
                vec![
                    Check::Title(show.to_string()),
                    Check::Kind(MediaKind::Episode),
                    Check::Season(0),
                    Check::Episode(episode),
                    Check::EpisodeEndNone,
                    Check::Absolute(false),
                ],
            )
        } else {
            let end = episode + 1;
            plain(
                "season_zero",
                format!("{show}.S00E{episode:02}E{end:02}.mkv"),
                vec![
                    Check::Title(show.to_string()),
                    Check::Kind(MediaKind::Episode),
                    Check::Season(0),
                    Check::Episode(episode),
                    Check::EpisodeEnd(end),
                    Check::Absolute(false),
                ],
            )
        };
        out.push(case);
    }
    out
}

fn build_extras_editions(count: usize, rng: &mut Rng, _max: usize) -> Vec<Case> {
    let mut out = Vec::with_capacity(count);
    for i in 0..count {
        let title = *rng.pick(FILM_TITLES);
        let year = rng.range(1900, 2019) as i32;
        let edition = *rng.pick(EDITIONS);
        let token = *rng.pick(RELEASE_TOKENS);
        let case = match i % 7 {
            0 => plain(
                "extras_editions",
                format!("{}.{year}.{edition}.1080p.mkv", dotted(title)),
                vec![
                    Check::Title(title.to_string()),
                    Check::Year(year),
                    Check::Kind(MediaKind::Movie),
                    Check::SeasonNone,
                    Check::EpisodeNone,
                ],
            ),
            1 => plain(
                "extras_editions",
                format!("{title} ({year}) {edition}.mkv"),
                vec![
                    Check::Title(title.to_string()),
                    Check::Year(year),
                    Check::Kind(MediaKind::Movie),
                    Check::SeasonNone,
                    Check::EpisodeNone,
                ],
            ),
            2 => plain(
                "extras_editions",
                format!("{}.{year}.{token}.1080p.BluRay.mkv", dotted(title)),
                vec![
                    Check::Title(title.to_string()),
                    Check::Year(year),
                    Check::Kind(MediaKind::Movie),
                    Check::SeasonNone,
                    Check::EpisodeNone,
                ],
            ),
            3 => {
                let show = *rng.pick(SHOW_NAMES);
                let season = rng.range(1, 12) as i32;
                let episode = rng.range(1, 30) as i32;
                plain(
                    "extras_editions",
                    format!("{show}.S{season:02}E{episode:02}.{edition}.1080p.mkv"),
                    vec![
                        Check::Title(show.to_string()),
                        Check::Kind(MediaKind::Episode),
                        Check::Season(season),
                        Check::Episode(episode),
                        Check::EpisodeEndNone,
                        Check::YearNone,
                    ],
                )
            }
            4 => {
                let show = *rng.pick(SHOW_NAMES);
                let season = rng.range(1, 12) as i32;
                let episode = rng.range(1, 30) as i32;
                plain(
                    "extras_editions",
                    format!("{show}.S{season:02}E{episode:02}.{token}.1080p.mkv"),
                    vec![
                        Check::Title(show.to_string()),
                        Check::Kind(MediaKind::Episode),
                        Check::Season(season),
                        Check::Episode(episode),
                        Check::EpisodeEndNone,
                        Check::YearNone,
                    ],
                )
            }
            5 => {
                // A season-extra: `Sxx` is the claim, and the extras numbering
                // behind it is not an episode.
                let show = *rng.pick(SHOW_NAMES);
                let season = rng.range(1, 12) as i32;
                plain(
                    "extras_editions",
                    format!("{show}.S{season:02}.Extras.01.Deleted.Scenes.720p.mkv"),
                    vec![
                        Check::Title(show.to_string()),
                        Check::Kind(MediaKind::Episode),
                        Check::Season(season),
                        Check::EpisodeNone,
                        Check::EpisodeEndNone,
                        Check::YearNone,
                        Check::Absolute(false),
                    ],
                )
            }
            _ => {
                let show = *rng.pick(SHOW_NAMES);
                let season = rng.range(1, 12) as i32;
                plain(
                    "extras_editions",
                    format!("{show} S{season:02} EXTRAS DVDRip XviD RUNNER.mkv"),
                    vec![
                        Check::Title(show.to_string()),
                        Check::Kind(MediaKind::Episode),
                        Check::Season(season),
                        Check::EpisodeNone,
                        Check::EpisodeEndNone,
                        Check::YearNone,
                        Check::Absolute(false),
                    ],
                )
            }
        };
        out.push(case);
    }
    out
}

fn build_misleading_tokens(count: usize, rng: &mut Rng, _max: usize) -> Vec<Case> {
    let mut out = Vec::with_capacity(count);
    for i in 0..count {
        let show = *rng.pick(SHOW_NAMES);
        let title = *rng.pick(FILM_TITLES);
        let season = rng.range(1, 12) as i32;
        let episode = rng.range(1, 30) as i32;
        let year = rng.range(1900, 2019) as i32;
        let case = match i % 7 {
            0 => plain(
                "misleading_tokens",
                format!("{show}.720p.mkv"),
                vec![
                    Check::Title(show.to_string()),
                    Check::YearNone,
                    Check::SeasonNone,
                    Check::EpisodeNone,
                ],
            ),
            1 => plain(
                "misleading_tokens",
                format!("{show}.1080p.x264.mkv"),
                vec![
                    Check::Title(show.to_string()),
                    Check::YearNone,
                    Check::SeasonNone,
                    Check::EpisodeNone,
                ],
            ),
            2 => plain(
                "misleading_tokens",
                format!("{show}.H.264.mkv"),
                vec![Check::YearNone, Check::SeasonNone, Check::EpisodeNone],
            ),
            3 => plain(
                "misleading_tokens",
                format!("{}.1080p.{year}.mkv", dotted(title)),
                vec![
                    Check::Title(title.to_string()),
                    Check::Year(year),
                    Check::Kind(MediaKind::Movie),
                    Check::SeasonNone,
                    Check::EpisodeNone,
                ],
            ),
            4 => plain(
                "misleading_tokens",
                format!("1923.S{season:02}E{episode:02}.mkv"),
                vec![
                    Check::Title("1923".to_string()),
                    Check::Kind(MediaKind::Episode),
                    Check::Season(season),
                    Check::Episode(episode),
                    Check::YearNone,
                ],
            ),
            5 => plain(
                "misleading_tokens",
                format!("{show}.S{season:02}E{episode:02}.1080p.x264.mkv"),
                vec![
                    Check::Title(show.to_string()),
                    Check::Kind(MediaKind::Episode),
                    Check::Season(season),
                    Check::Episode(episode),
                    Check::EpisodeEndNone,
                ],
            ),
            _ => plain(
                "misleading_tokens",
                format!("{show}.S01E00.mkv"),
                vec![
                    Check::Title(format!("{show} S01E00")),
                    Check::Kind(MediaKind::Movie),
                    Check::SeasonNone,
                    Check::EpisodeNone,
                ],
            ),
        };
        out.push(case);
    }
    out
}

fn build_malformed_size(count: usize, rng: &mut Rng, max_input_bytes: usize) -> Vec<Case> {
    let _ = rng;
    let absent = || vec![Check::SeasonNone, Check::EpisodeNone, Check::YearNone];
    let junk = [
        "", "   ", ".", "..", "......", ".......", "((((((((", "))))))))", "[[[[[[[[", "_._._._",
    ];
    let weird = [
        "Show...mkv",
        "Show..S01E01...mkv",
        "Show.S01E01.",
        "Show.S01E01....mkv",
    ];
    let mut cases = Vec::with_capacity(count);
    for name in junk {
        cases.push(plain("malformed_size", name.to_string(), absent()));
    }
    for name in weird {
        // These still parse as ordinary names; the family asserts only that the
        // parser stays bounded and does not panic on them.
        cases.push(plain("malformed_size", name.to_string(), Vec::new()));
    }
    cases.push(plain(
        "malformed_size",
        "x".repeat(max_input_bytes),
        absent(),
    ));
    let marker = ".S01E02.mkv";
    let padded = format!("{}{marker}", "x".repeat(max_input_bytes - marker.len()));
    cases.push(plain(
        "malformed_size",
        padded,
        vec![Check::Season(1), Check::Episode(2)],
    ));
    // Return the distinct inputs directly. The declared count must equal this
    // population, so a modulo repeat can never overstate it again.
    assert_eq!(
        cases.len(),
        count,
        "malformed_size has {} distinct inputs but declares {count}",
        cases.len()
    );
    cases
}

/// FNV-1a 64-bit, used only as a determinism fingerprint over the generated
/// inputs. It is not a security hash.
const FNV_OFFSET: u64 = 0xcbf2_9ce4_8422_2325;
const FNV_PRIME: u64 = 0x0000_0100_0000_01b3;

fn fnv1a_update(mut hash: u64, bytes: &[u8]) -> u64 {
    for &byte in bytes {
        hash ^= u64::from(byte);
        hash = hash.wrapping_mul(FNV_PRIME);
    }
    hash
}

fn fingerprint(cases: &[Case]) -> u64 {
    let mut hash = FNV_OFFSET;
    for case in cases {
        hash = fnv1a_update(hash, case.family.as_bytes());
        hash = fnv1a_update(hash, b"\0");
        hash = fnv1a_update(hash, case.input.as_bytes());
        hash = fnv1a_update(hash, b"\0");
    }
    hash
}

fn generate_all(seed: u64, max_input_bytes: usize) -> Vec<Case> {
    let mut out = Vec::new();
    for (name, count, builder) in FAMILIES {
        let mut rng = Rng::new(seed ^ fnv1a_update(FNV_OFFSET, name.as_bytes()));
        out.extend(builder(count, &mut rng, max_input_bytes));
    }
    out
}

fn parse_case(case: &Case) -> ParsedName {
    match &case.mode {
        Mode::Plain => parse_filename(&case.input),
        Mode::Folder {
            folder_title,
            season,
        } => parse_filename_in(
            &case.input,
            FolderContext {
                folder_title: folder_title.as_deref(),
                season: *season,
            },
        ),
        Mode::Parent(parent_name) => parse_with_parent(&case.input, Some(parent_name)),
    }
}

fn check_case(case: &Case, parsed: &ParsedName) -> Result<(), String> {
    for check in &case.checks {
        let ok = match check {
            Check::Title(title) => parsed.title == *title,
            Check::Kind(kind) => parsed.kind == *kind,
            Check::Year(year) => parsed.year == Some(*year),
            Check::YearNone => parsed.year.is_none(),
            Check::Season(season) => parsed.season == Some(*season),
            Check::SeasonNone => parsed.season.is_none(),
            Check::Episode(episode) => parsed.episode == Some(*episode),
            Check::EpisodeNone => parsed.episode.is_none(),
            Check::EpisodeEnd(end) => parsed.episode_end == Some(*end),
            Check::EpisodeEndNone => parsed.episode_end.is_none(),
            Check::Absolute(absolute) => parsed.episode_absolute == *absolute,
        };
        if !ok {
            return Err(format!(
                "family {} input {:?} failed {check:?}: got {parsed:?}",
                case.family, case.input
            ));
        }
    }
    Ok(())
}

fn check_input_bound(case: &Case, max_input_bytes: usize) -> Result<(), String> {
    if case.input.len() > max_input_bytes {
        return Err(format!(
            "input bound: family {} input is {} bytes, over {max_input_bytes}",
            case.family,
            case.input.len()
        ));
    }
    Ok(())
}

fn expected_families() -> BTreeMap<String, usize> {
    FAMILIES
        .iter()
        .map(|(name, count, _)| ((*name).to_string(), *count))
        .collect()
}

fn manifest_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/naming/stress/manifest.json")
}

fn parse_hex_u64(text: &str) -> Result<u64, String> {
    u64::from_str_radix(text.strip_prefix("0x").unwrap_or(text), 16)
        .map_err(|e| format!("hex {text:?}: {e}"))
}

fn parse_manifest(value: &Value) -> Result<Manifest, String> {
    let mut families = BTreeMap::new();
    for (name, count) in value["families"]
        .as_object()
        .ok_or("families is not an object")?
    {
        families.insert(
            name.clone(),
            count.as_u64().ok_or("family count is not a number")? as usize,
        );
    }
    Ok(Manifest {
        schema_version: value["schema_version"].as_i64().ok_or("schema_version")?,
        generator_version: value["generator_version"]
            .as_i64()
            .ok_or("generator_version")?,
        seed: parse_hex_u64(value["seed"].as_str().ok_or("seed")?)?,
        total_cases: value["total_cases"].as_u64().ok_or("total_cases")? as usize,
        families,
        max_input_bytes: value["max_input_bytes"].as_u64().ok_or("max_input_bytes")? as usize,
        local_case_budget: value["local_case_budget"]
            .as_u64()
            .ok_or("local_case_budget")? as usize,
        local_byte_budget: value["local_byte_budget"]
            .as_u64()
            .ok_or("local_byte_budget")?,
        fingerprint: parse_hex_u64(
            value["fingerprint_fnv1a64"]
                .as_str()
                .ok_or("fingerprint_fnv1a64")?,
        )?,
    })
}

fn load_manifest() -> Result<Manifest, String> {
    let text =
        std::fs::read_to_string(manifest_path()).map_err(|e| format!("read manifest: {e}"))?;
    let value: Value = serde_json::from_str(&text).map_err(|e| format!("manifest JSON: {e}"))?;
    parse_manifest(&value)
}

/// Validate the recorded manifest against the code constants and the generated
/// population. Every guard has a mutation control below.
fn validate_manifest(manifest: &Manifest) -> Result<(), String> {
    if manifest.schema_version != SCHEMA_VERSION {
        return Err(format!(
            "schema_version {} is not {SCHEMA_VERSION}",
            manifest.schema_version
        ));
    }
    if manifest.generator_version != GENERATOR_VERSION {
        return Err(format!(
            "generator_version {} is not {GENERATOR_VERSION}",
            manifest.generator_version
        ));
    }
    if manifest.seed != SEED {
        return Err(format!(
            "seed 0x{:016x} is not the declared 0x{SEED:016x}",
            manifest.seed
        ));
    }
    let expected = expected_families();
    if manifest.families != expected {
        return Err(format!(
            "family accounting mismatch: manifest {:?} is not code {:?}",
            manifest.families, expected
        ));
    }
    let total: usize = expected.values().sum();
    if manifest.total_cases != total {
        return Err(format!(
            "total_cases {} is not {total}",
            manifest.total_cases
        ));
    }
    if manifest.max_input_bytes != MAX_INPUT_BYTES {
        return Err(format!(
            "max_input_bytes {} is not {MAX_INPUT_BYTES}",
            manifest.max_input_bytes
        ));
    }
    if manifest.local_case_budget != LOCAL_CASE_BUDGET {
        return Err(format!(
            "local_case_budget {} is not {LOCAL_CASE_BUDGET}",
            manifest.local_case_budget
        ));
    }
    if manifest.local_byte_budget != LOCAL_BYTE_BUDGET {
        return Err(format!(
            "local_byte_budget {} is not {LOCAL_BYTE_BUDGET}",
            manifest.local_byte_budget
        ));
    }
    if manifest.local_case_budget > HARD_MAX_CASES {
        return Err(format!(
            "local_case_budget {} is over the hard cap {HARD_MAX_CASES}",
            manifest.local_case_budget
        ));
    }
    if manifest.max_input_bytes > HARD_MAX_INPUT_BYTES {
        return Err(format!(
            "max_input_bytes {} is over the hard cap {HARD_MAX_INPUT_BYTES}",
            manifest.max_input_bytes
        ));
    }
    if manifest.local_byte_budget > HARD_MAX_BYTES {
        return Err(format!(
            "local_byte_budget {} is over the hard cap {HARD_MAX_BYTES}",
            manifest.local_byte_budget
        ));
    }

    let cases = generate_all(SEED, MAX_INPUT_BYTES);
    if cases.len() > manifest.local_case_budget {
        return Err(format!(
            "generated {} cases over the {LOCAL_CASE_BUDGET} budget",
            cases.len()
        ));
    }
    let bytes: u64 = cases.iter().map(|case| case.input.len() as u64).sum();
    if bytes > manifest.local_byte_budget {
        return Err(format!(
            "generated {bytes} bytes over the {LOCAL_BYTE_BUDGET} budget"
        ));
    }
    let actual = fingerprint(&cases);
    if actual != manifest.fingerprint {
        return Err(format!(
            "fingerprint 0x{actual:016x} is not the recorded 0x{:016x}",
            manifest.fingerprint
        ));
    }
    Ok(())
}

#[test]
fn generated_stress_cases_hold_declared_conventions() {
    let start = Instant::now();
    let manifest = load_manifest().unwrap();
    validate_manifest(&manifest).unwrap();

    let cases = generate_all(SEED, MAX_INPUT_BYTES);
    let expected_total: usize = FAMILIES.iter().map(|(_, count, _)| count).sum();
    assert_eq!(
        cases.len(),
        expected_total,
        "generated total differs from the declared family counts"
    );
    for (name, count, _) in FAMILIES {
        assert!(count > 0, "family {name} declares no cases");
        let generated = cases.iter().filter(|case| case.family == name).count();
        assert_eq!(
            generated, count,
            "family {name} generated {generated} cases, declared {count}"
        );
    }

    for case in &cases {
        check_input_bound(case, MAX_INPUT_BYTES).unwrap();
        let parsed = parse_case(case);
        check_case(case, &parsed).unwrap_or_else(|e| panic!("{e}"));
    }

    let bytes: usize = cases.iter().map(|case| case.input.len()).sum();
    println!(
        "stress observation: {} cases, {} input bytes, generated and checked in {:?} (local run)",
        cases.len(),
        bytes,
        start.elapsed()
    );
}

#[test]
fn expected_field_mutation_is_caught() {
    let cases = generate_all(SEED, MAX_INPUT_BYTES);
    let mut case = cases
        .iter()
        .find(|case| case.family == "sxxeyy_nxnn")
        .expect("no sxxeyy_nxnn case to mutate")
        .clone();
    let mut mutated = false;
    for check in &mut case.checks {
        if let Check::Title(title) = check {
            *title = "A Different Show".to_string();
            mutated = true;
        }
    }
    assert!(mutated, "the sample case had no title check to mutate");
    let parsed = parse_case(&case);
    let err = check_case(&case, &parsed).unwrap_err();
    assert!(err.contains("Title"), "{err}");
}

#[test]
fn family_accounting_mutation_is_caught() {
    let mut manifest = load_manifest().unwrap();
    *manifest
        .families
        .get_mut("sxxeyy_nxnn")
        .expect("sxxeyy_nxnn family") += 1;
    let err = validate_manifest(&manifest).unwrap_err();
    assert!(err.contains("family accounting"), "{err}");
}

#[test]
fn seed_mutation_is_caught() {
    let mut manifest = load_manifest().unwrap();
    manifest.seed ^= 1;
    let err = validate_manifest(&manifest).unwrap_err();
    assert!(err.contains("seed"), "{err}");

    let base = fingerprint(&generate_all(SEED, MAX_INPUT_BYTES));
    let altered = fingerprint(&generate_all(SEED ^ 1, MAX_INPUT_BYTES));
    assert_ne!(
        base, altered,
        "changing the seed did not change the generated cases"
    );
}

#[test]
fn input_bound_mutation_is_caught() {
    let case = Case {
        family: "malformed_size",
        input: "x".repeat(MAX_INPUT_BYTES + 1),
        mode: Mode::Plain,
        checks: Vec::new(),
    };
    let err = check_input_bound(&case, MAX_INPUT_BYTES).unwrap_err();
    assert!(err.contains("input bound"), "{err}");
}
